In [1]:
import matplotlib.pyplot as plt
from math import log, log10, e, pi,cos,sin
from numpy import *
import cmath
from cmath import pi, exp
from mpl_toolkits import mplot3d
from sympy import *
import numpy as np
import math

In [15]:
u=5+12j
print("complex to polar",cmath.polar(u)) #complex to polar
print("magnitude",abs(u)) #크기 magnitude
print("phase",rad2deg(cmath.phase(u)))#radian to degree
a = cmath.polar(u)
print("polar form to rectangular form",cmath.rect(a[0], a[1]))

complex to polar (13.0, 1.176005207095135)
magnitude 13.0
phase 67.38013505195957
polar form to rectangular form (5.000000000000001+12j)


In [5]:
print(cmath.polar(u))

(5.830951894845301, 1.0303768265243125)


Z = x + jy   »  Rectangular Form
<br>
Z = A ∠Φ   »  Polar Form
<br>
Z = A e jΦ   »  Exponential Form

In [24]:
v=1+2j
w=3+4j
print(v+w)
print(v*w)
print(conj(v)) #conjugate
print(arg(w))

(4+6j)
(-5+10j)
(1-2j)
0.927295218001612


In [48]:
cmath.rect(2,pi/6)+cmath.rect(4,pi/3)

(3.7320508075688767+4.464101615137755j)

In [32]:
# Numpy Matrix Operations
import numpy as np

A = np.array([[2, 4],
              [5, -6]])
B = np.array([[9, -3],
              [3, 6]])
C = A + B      # element wise addition
D = A - B      # element wise subtraction
print("A+B\n",C)
print("\nA-B\n",D)

E = np.array([[3, 6, 7], 
              [5, -3, 0]]) #2*3
F = np.array([[1, 1], 
              [2, 1], 
              [3, -3]]) #3*2
C = E.dot(F)   # matrix multiplication
print("\nA*B\n",C)

A = np.array([[1, 1],
              [2, 1],
              [3, -3]])
print("\ntranpose\n",A.transpose())
print("\n determinant of A.",np.linalg.det(B))
print("\ninverse\n",np.linalg.inv(B))

A+B
 [[11  1]
 [ 8  0]]

A-B
 [[ -7   7]
 [  2 -12]]

A*B
 [[ 36 -12]
 [ -1   2]]

tranpose
 [[ 1  2  3]
 [ 1  1 -3]]

 determinant of A. 62.99999999999999

inverse
 [[ 0.0952381   0.04761905]
 [-0.04761905  0.14285714]]


In [36]:
#2) For A = [1 2 3; 4 5 6; 1 1 3], answer the following questions:
#Use numpy.array for creating A so that you can use slicing indices.
A = np.array([[1, 0, -1],[ 0, 1, 1],[ 1 ,-1 ,0]])

#a) Let aij be the element of ith row and jth column of A. Find a23.
print("a : ",A[1][2]) #3rd element of 2nd row

#b) Find 3rd row of A.
print("\nb : ",A[2])

#c) Find 2nd column of A.
print("\nc : ",A[:,1])

#d) Find the transpose of A.
print("\nd : \n",A.transpose())

#e) Find the number of independent rows or columns of A.
#Use numphy function of numpy.linalg.matrix_rank(A)
print("\ne : ",np.linalg.matrix_rank(A))

#f) Find the inverse of A.
print("\nf : \n",np.linalg.inv(A))

#i) Find the sum of the diagonal elements of A.
print("\ni : ",np.trace(A))
#j) Find the determinant of A.
print("\nj : ",np.linalg.det(A))
#k) Find the adjoint matrix of A and the inverse matrix of A using (j).
print("\nk : adjoint matrix of A\n",np.linalg.det(A)*np.linalg.inv(A))
print("\nk : inverse matrix of A \n",np.linalg.inv(A))

a :  1

b :  [ 1 -1  0]

c :  [ 0  1 -1]

d : 
 [[ 1  0  1]
 [ 0  1 -1]
 [-1  1  0]]

e :  3

f : 
 [[ 0.5  0.5  0.5]
 [ 0.5  0.5 -0.5]
 [-0.5  0.5  0.5]]

i :  2

j :  2.0

k : adjoint matrix of A
 [[ 1.  1.  1.]
 [ 1.  1. -1.]
 [-1.  1.  1.]]

k : inverse matrix of A 
 [[ 0.5  0.5  0.5]
 [ 0.5  0.5 -0.5]
 [-0.5  0.5  0.5]]


In [ ]:
#3) Find the solution of the following linear equations.

#2x-3y+z = 1
#4x-y+2z=3
#5x-2y+3z=-2

B = np.array([[2,-3,1], 
              [4,-1,2],
              [5,-2,3]])

inv_B = np.linalg.inv(B)

C =np.array([1,3,-2])

X = inv_B.dot(C)

print("3)  x=    y=   z=\n",X)


In [ ]:
# Slicing of a Matrix
import numpy as np

letters = np.array([1, 3, 5, 7, 9, 7, 5])

print(letters[2:5])        # 3rd to 5th elements
print(letters[:-5])        # 1st to (last-5)th elements
print(letters[5:])         # 6th to last elements
print(letters[:])          # 1st to last elements
print(letters[::-1])       # reversing a list
print()

A = np.array([[1, 4, 5, 12, 14], 
    [-5, 8, 9, 0, 17],
    [-6, 7, 11, 19, 21]])

print(A[:2, :4])   # two rows, four columns
print(A[:1,])      # first row, all columns
print(A[:,2])      # all rows, second column
print(A[:, 2:5])   # all rows, third to fifth column


In [ ]:
#2) For A = [1 2 3; 4 5 6; 1 1 3], answer the following questions:
#Use numpy.array for creating A so that you can use slicing indices.
A = np.array([[1,2,3], 
              [4,5,6],
              [1,1,3]])

#a) Let aij be the element of ith row and jth column of A. Find a23.
print("a : ",A[1][2]) #3rd element of 2nd row

#b) Find 3rd row of A.
print("\nb : ",A[2])

#c) Find 2nd column of A.
print("\nc : ",A[:,1])

#d) Find the transpose of A.
print("\nd : \n",A.transpose())

#e) Find the number of independent rows or columns of A.
#Use numphy function of numpy.linalg.matrix_rank(A)
print("\ne : ",np.linalg.matrix_rank(A))

#f) Find the inverse of A.
print("\nf : \n",np.linalg.inv(A))

#i) Find the sum of the diagonal elements of A.
print("\ni : ",np.trace(A))
#j) Find the determinant of A.
print("\nj : ",np.linalg.det(A))
#k) Find the adjoint matrix of A and the inverse matrix of A using (j).
print("\nk : adjoint matrix of A\n",np.linalg.det(A)*np.linalg.inv(A))
print("\nk : inverse matrix of A \n",np.linalg.inv(A))

In [ ]:
delx = 0.1

t = np.arange(0, 2.1, delx)
a = [0, 9.05, 16.37, 22.22, 26.81, 30.33, 32.93, 34.76, 35.95, 36.59, 36.79, 36.62, 36.14, 35.43, 34.52, 33.47, 32.30, 31.06, 29.75, 28.42, 27.07]
v = delx*np.cumsum(a)
d = delx*np.cumsum(v)
plt.title('red: velocity, blue: displacement')
plt.plot(t, v, '-r', t, d, '-b')


In [33]:
x=5
np.log(5)

1.6094379124341003

In [35]:
#3) Find the solution of the following linear equations.

#2x-3y+z = 1
#4x-y+2z=3
#5x-2y+3z=-2

B = np.array([[3,2],[2,-1]])

inv_B = np.linalg.inv(B)
print(inv_B)
C =np.array([13,4])

X = inv_B.dot(C)

print("3)  x=    y=   z=\n",X)


[[ 0.14285714  0.28571429]
 [ 0.28571429 -0.42857143]]
3)  x=    y=   z=
 [3. 2.]


In [18]:
t = array(np.arange(0, 3, 0.001))
m = np.ones(len(t))

phasor1 = m * np.exp(1j*2*pi*t)
phasor2 = (2*m) * np.exp(1j*2*pi*4*t)

print(phasor1*phasor2)

TypeError: 'DeprecatedImportModule' object is not callable

In [ ]:
# Vector is an one dimensional array
import numpy as np

x = np.array([3,1/2,2])   # vector x
y = np.array([2,2,1])   # vector y

print(x + y)            # vector addition
print(x - y)            # vector subtraction
dot = np.dot(x, y)      # vectot dot product
print(dot)     # vectot dot product

x_norm = np.sqrt((x*x).sum()) # magnitude of x
y_norm = np.linalg.norm(y)    # magnitude of y
print(x_norm, y_norm)
cos_angle = dot / (x_norm * y_norm) # cosine of angle between x and y
angle = np.arccos(cos_angle)
function1 = [10, 0, 0, 0, 0]
y1 = np.poly1d(function1) # 4*x**4 

print(y1)

In [49]:
u = np.array([7,-7,7])   # vector x
v = np.array([-6,2,-3])   # vector y
  
# Task: Project vector u on vector v 
  
# finding norm of the vector v 
v_norm = np.sqrt(sum(v**2))     
  
# Apply the formula as mentioned above 
# for projecting a vector onto another vector 
# find dot product using np.dot() 
proj_of_u_on_v = (np.dot(u, v)/v_norm**2)*v 
  
print("Projection of Vector u on Vector v is: ", proj_of_u_on_v) 


Projection of Vector u on Vector v is:  [ 9.42857143 -3.14285714  4.71428571]


In [43]:
A =np.array( [[2, 0],[3, 7]])

print(np.linalg.det(A))


14.000000000000004


In [44]:
A=np.array([[cos(pi/3) ,-sin(pi/3)],
           [sin(pi/3), cos(pi/3)]])

In [47]:
B=np.array([[2,0],[0,5]])
A =np.array( [[2, 0],[3, 7]])
C=B.dot(A)
print(C)

[[ 4  0]
 [15 35]]


In [ ]:
[[1,0],[0,-1]]